'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import App from './app'
const inter = Inter({ subsets: ['latin'] })
import ReduxProvider from '@/redux/provider'


// export const metadata: Metadata = {
//   title: 'Food Lovers',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <App>
            {children}
          </App>
        </ReduxProvider>
      </body>
    </html>
  )
}
